language: node_js
services:
  - docker
node_js:
  - "node"
before_install:
  - docker build -t reverentengineer/restful_wedding .
  - docker run reverentengineer/restful_Wedding /bin/sh -c "npm install && npm test"
