language: node_js
services:
  - docker
node_js:
  - "11"
before_install:
  - docker build -t reverentengineer/restful_wedding .
  - docker run reverentengineer/restful_wedding /bin/sh -c "npm install --only=dev && npm test"
